#!/usr/bin/env bash

# Enable bash completion
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

# Turn off the annoying bell
[[ $- == *i* ]] && bind "set bell-style none"

# Expand the history size
export HISTFILESIZE=5000
export HISTSIZE=500
export HISTTIMEFORMAT="%F %T"

# Don't put duplicate lines in the history
export HISTCONTROL=erasedups

# Check and update the window size after each command.
shopt -s checkwinsize

# Append to history instead of overwriting it
shopt -s histappend

# Instantly update history (now available in other windows)
PROMPT_COMMAND='history -a'

# Set the default editor
export EDITOR=nvim
export Visual=nvim
alias vim='nvim'

# Add colors for ls and grep commands
export LS_COLORS='no=00:fi=00:di=00;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:*.xml=00;31:'

# Color for manpages in less makes manpages a little easier to read
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Case insensitive completion
bind 'set completion-ignore-case on'
bind 'set show-all-if-ambiguous on'

###########
# ALIASES #
###########

# Better mkdir
alias mkdir='mkdir -p'

# Add colors and file type extensions
alias ls='ls -aFh --color=always'

# Add colors to grep
alias grep='grep --color=auto'

# Automatically install the needed support files for this .bashrc file
install_bashrc_support() {
  local packages=(
    fastfetch
    bash-completion
    fzf
  )
  
  echo "Installing bashrc dependencies..."
  sudo pacman -S --needed "${packages[@]}"
  
  echo "Done. Restart your shell or run 'source ~/.bashrc'"
}

##########
# PROMPT #
##########

# Color definitions for prompt
_reset='\[\e[0m\]'
_bold_brown='\[\e[1;33m\]'
_bold_purple='\[\e[1;35m\]'
_bold_green='\[\e[1;32m\]'
_bold_red='\[\e[1;31m\]'
_green='\[\e[0;32m\]'
_purple='\[\e[0;35m\]'
_red='\[\e[0;31m\]'
_teal='\[\e[0;36m\]'
_white='\[\e[0;37m\]'

function _git_prompt {
  git rev-parse --is-inside-work-tree &>/dev/null || return

  local branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
  local status_flags=""
  
  local staged=$(git diff --staged --numstat 2>/dev/null | wc -l)
  local unstaged=$(git diff --numstat 2>/dev/null | wc -l)
  local untracked=$(git ls-files --others --exclude-standard 2>/dev/null | wc -l)
  
  [[ $staged -gt 0 ]] && status_flags+="${_bold_green}+${staged}${_reset}"
  [[ $unstaged -gt 0 ]] && status_flags+="${_bold_red}~${unstaged}${_reset}"
  [[ $untracked -gt 0 ]] && status_flags+="${_white}?${untracked}${_reset}"
  
  [[ -z $status_flags ]] && status_flags="${_bold_green}✓${_reset}"
  
  echo "[${_bold_green}±${_reset}][${branch} ${status_flags}]"
}

function _venv_prompt {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    local venv_name=$(basename "$VIRTUAL_ENV")
    echo "[${_purple}${venv_name}${_reset}]"
  else
    echo "[${_white}raw${_reset}]"
  fi
}

function _prompt_command {
  local last_exit=$?
  local border_color

  if [[ $last_exit -ne 0 ]]; then
    border_color="$_red"
  else
    border_color="$_reset"
  fi

  PS1="${border_color}┌─${_reset}[${_teal}\W${_reset}]$(_git_prompt)$(_venv_prompt)"$'\n'
  PS1+="${border_color}└─▪${_reset} "
}

PROMPT_COMMAND='_prompt_command; history -a'
PS2="└─▪ "
