# Set mainMod
$mainMod = SUPER

# Workspaces (QWERTY row for Corne)
bind = $mainMod, Q, workspace, 1
bind = $mainMod, W, workspace, 2
bind = $mainMod, E, workspace, 3
bind = $mainMod, R, workspace, 4
bind = $mainMod, T, workspace, 5
bind = $mainMod, Y, workspace, 6
bind = $mainMod, U, workspace, 7
bind = $mainMod, I, workspace, 8
bind = $mainMod, O, workspace, 9
bind = $mainMod, P, workspace, 10

# Move to workspace
bind = $mainMod SHIFT, Q, movetoworkspace, 1
bind = $mainMod SHIFT, W, movetoworkspace, 2
bind = $mainMod SHIFT, E, movetoworkspace, 3
bind = $mainMod SHIFT, R, movetoworkspace, 4
bind = $mainMod SHIFT, T, movetoworkspace, 5
bind = $mainMod SHIFT, Y, movetoworkspace, 6
bind = $mainMod SHIFT, U, movetoworkspace, 7
bind = $mainMod SHIFT, I, movetoworkspace, 8
bind = $mainMod SHIFT, O, movetoworkspace, 9
bind = $mainMod SHIFT, P, movetoworkspace, 10
